FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt || pip install --no-cache-dir --default-timeout=100 -r requirements.txt

COPY backend/ .

# Verify model exists
RUN ls -l trained_models/Trained_model.h5 || echo "Model file is missing!"

# Add environment variable to suppress TensorFlow warnings
ENV TF_CPP_MIN_LOG_LEVEL=2

CMD ["python", "app.py"] 